[project]
name = "aoc-2015"
version = "0.1.0"
description = "Base for advent of code 2015 solutions"
readme = "README.md"
requires-python = ">=3.13"
dependencies = []

[dependency-groups]
dev = [
    "pytest>=8.3.5",
]

[tool.uv]
package = true
